Initial integration of TelemetryAwarePlugin to ISM
opensearch-project/index-management pull request #1186
Opened 2024-06-11 07:28 UTC by harshitakaushik-dev

*Description of changes:*

- Initialised TelemetryAwarePlugin in IndexManagementPlugin.kt 
- Created IndexManagementActionsMetrics.kt which defines a singleton class IndexManagementActionsMetrics that provides metrics for different OpenSearch Index Management actions (like rollover) by registering them with a metrics registry.

*CheckList:*
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/index-management/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-06-11 11:47 UTC, sarthakaggarwal97 commented on src/main/kotlin/org/opensearch/indexmanagement/IndexManagementPlugin.kt
> +import org.opensearch.indexmanagement.indexstatemanagement.*
please do not use wildcard

2024-06-11 11:48 UTC, sarthakaggarwal97 commented on src/main/kotlin/org/opensearch/indexmanagement/IndexManagementPlugin.kt
> +import org.opensearch.plugins.*
same, please remove wildcard

2024-06-11 11:50 UTC, sarthakaggarwal97 commented on src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/IndexManagementActionsMetrics.kt
> +            "rollover" to RolloverActionMetrics(metricsRegistry),
this is not defined yet, please remove this for now. We can populate the map in the subsequent PR

2024-06-12 17:27 UTC, harshitakaushik-dev commented on src/main/kotlin/org/opensearch/indexmanagement/IndexManagementPlugin.kt
> +import org.opensearch.plugins.*
Yes, I've made the updates in the new commit.

2024-06-12 17:40 UTC, sarthakaggarwal97 commented
@harshitakaushik-dev thanks for iteration, would you please add some UTs to verify the behavior in the next iteration. Also, please check some lint related gradle tasks seem to be failing.

2024-06-13 05:23 UTC, sarthakaggarwal97 commented
@bowenlan-amzn @Gaganjuneja it would be great if you guys can take a look!

The file diff id huge, but its mostly change in arguments of a function. The change for one action would somewhat look like this [commit](https://github.com/opensearch-project/index-management/pull/1186/commits/681d015cd457372ab5cee88fdf21d2640a27abdc)

2024-06-13 15:19 UTC, bowenlan-amzn commented
[**@sarthakaggarwal97**](https://github.com/sarthakaggarwal97) commented on [Jun 12, 2024, 10:23 PM PDT](https://github.com/opensearch-project/index-management/pull/1186#issuecomment-2164408196 "2024-06-13T05:23:06Z - Replied by Github Reply Comments"):
> @bowenlan-amzn @Gaganjuneja it would be great if you guys can take a look!
> 
> The file diff id huge, but its mostly change in arguments of a function. The change for one action would somewhat look like this [commit](https://github.com/opensearch-project/index-management/pull/1186/commits/681d015cd457372ab5cee88fdf21d2640a27abdc)
> 
> _Originally posted by @sarthakaggarwal97 in https://github.com/opensearch-project/index-management/issues/1186#issuecomment-2164408196_

Really like this change, with metrics, user can setup alarm instead of only relying on the error notifications, which is a long-asking feature. 
I will go through this later. Before that, can we have a GitHub issue for this that's public facing and later on copied to documentation.

2024-06-18 05:14 UTC, r1walz requested changes
Thanks for PR @harshitakaushik-dev! It's a good start. Can you please look into the check failures and fix the cause. Thanks!

2024-06-18 05:14 UTC, r1walz commented on spi/src/main/kotlin/org.opensearch.indexmanagement.spi/indexstatemanagement/metrics/IndexManagementActionsMetrics.kt
> +        RolloverActionMetrics.instance.initializeCounters(metricsRegistry, "rollover")
"rollover" is getting repeated too many times. Let's create a const instead and use that to remediate making mistakes (spelling error) at other usages.

2024-06-18 05:14 UTC, r1walz commented on spi/src/main/kotlin/org.opensearch.indexmanagement.spi/indexstatemanagement/metrics/IndexManagementActionsMetrics.kt
> +            "rollover" to RolloverActionMetrics.instance,
Have "rollover" as const.

2024-06-18 05:14 UTC, r1walz commented on src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/rollover/AttemptRolloverStep.kt
> +        this.indexManagementActionsMetrics = indexManagementActionsMetrics
Do we use it after assignment? What's the need here?

2024-06-18 05:14 UTC, r1walz commented on src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/rollover/AttemptRolloverStep.kt
> +        this.actionMetrics = indexManagementActionsMetrics.getActionMetrics("rollover") as RolloverActionMetrics
Use "rollover" as const.

2024-06-18 05:14 UTC, r1walz commented on src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/rollover/AttemptRolloverStep.kt
> +            )
Should this be encapsulated inside of `RolloverActionMetrics`/`ActionMetrics` itself?

2024-06-18 05:14 UTC, r1walz commented on src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/rollover/AttemptRolloverStep.kt
> +    override suspend fun execute(indexManagementActionsMetrics: IndexManagementActionsMetrics): Step {
Corresponding param in super class (Step) doesn't match the param name here. It will result in compilation failures.

2024-06-20 08:51 UTC, harshitakaushik-dev commented
@r1walz Made the requested changes in the new PR with additional action metrics. Request you to kindly review PR #1195

2024-06-20 08:51 UTC, closed without merging