Use disk stats, not RAM, for shrink action and node evaluation.
opensearch-project/index-management pull request #418
Opened 2022-07-19 15:45 UTC by linuxboyng

2022-07-19 16:07 UTC, downsrob commented
Our developer certificate of origin check is failing, would you mind signing off your commit and force pushing?
You can sign it with:
```
git commit --amend --signoff
```
See here https://github.com/opensearch-project/.github/blob/main/CONTRIBUTING.md#developer-certificate-of-origin for more information

2022-07-19 16:13 UTC, downsrob requested changes

2022-07-19 16:13 UTC, downsrob commented on src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/shrink/AttemptMoveShardsStep.kt
>          const val OS_METRIC = "os"
Can you change line 270 to FS_METRIC, and remove this constant?

2022-07-19 16:13 UTC, downsrob commented on src/test/kotlin/org/opensearch/indexmanagement/indexstatemanagement/util/StepUtilsTests.kt
> +// import org.opensearch.monitor.os.OsStats
You can remove this commented out import as well, please.

2022-07-19 16:13 UTC, downsrob commented on src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/shrink/AttemptShrinkStep.kt
> +        val nodesStatsReq = NodesStatsRequest().addMetrics(AttemptMoveShardsStep.OS_METRIC, AttemptMoveShardsStep.FS_METRIC)
You can remove the OS_METRIC entirely, we aren't using it at all anymore

2022-07-19 17:14 UTC, linuxboyng commented
Making those suggested changes now.

2022-07-19 20:09 UTC, linuxboyng commented
Pushed changes to my fork on same branch.

2022-07-19 20:20 UTC, downsrob commented
Thanks! Code changes look great. Last thing is that your commits still need to be signed off.
If your user.name and user.email are set in your git configs you can use this to sign off your last two commits
```
git rebase --signoff HEAD~2
```
Then just force push the change. 
Otherwise, you can just add `Signed-off-by: Your Name <your.email@email.com>` to the end of each of your commit messages directly. By the way, you will need to use your real name, we don't accept pseudonyms or anonymous contributors.

2022-07-19 21:05 UTC, downsrob commented
No worries. We are almost there, but I see that your first two commits are still failing DCO check as those aren't signed off. Can you amend these two: 3afe1b3, ac6959c and force push?

2022-07-20 16:13 UTC, linuxboyng commented
Sorry but my git knowledge is limited.  How would I amend those two specific commits?  I tried doing a `git checkout ac6959c` then `git commit --amend --signoff` but it keeps getting rejected with the error `Updates were rejected because a pushed branch tip is behind its remote counterpart` .  Would it be easier to just redo the entire process again?

2022-07-20 16:37 UTC, downsrob commented
To sign all of your commits (the last 6) you can use this:
```
git rebase HEAD~6 --signoff
```
Your changes are rewriting the commit history, so you will need to force push. You can just use this:
```
git push --force
```

2022-07-20 16:41 UTC, linuxboyng commented
Done.  Ty again!

2022-07-20 17:09 UTC, downsrob commented
Ok, so it looks like you removed some of your commits so when you signed off the batch of previous commits, you ended up modifying two existing commits from main. Now those commits are being included in this PR. We don't want to rewrite those changes so we will have to undo that. There are a lot of ways to fix this but the easiest one will be to just reset the commit history, add a new commit, and then push.
Here is what I will recommend:
First just make a backup branch in case we break everything here, we don't want to lose the code. Then go back to this branch.
```
git checkout use_diskstats_for_shrink
git checkout -b backup-shrink-fix
git checkout use_diskstats_for_shrink
```
Reset your git history to main, this will keep your file changes but reset the git history.
```
git reset --soft origin/main
```
Then just create a new commit with your changes:
```
git commit -m "Use disk stats, not RAM, for shrink action and node evaluation." --signoff
```
Now force push as you will be modifying the history of the pull request:
```
git push --force
```

2022-07-21 04:13 UTC, linuxboyng commented
I ran your suggested git commands.  Hopefully I did it correct this time.

2022-07-21 17:49 UTC, downsrob approved these changes

2022-07-21 18:06 UTC, bowenlan-amzn approved these changes
Thanks for the change!

2022-07-21 18:09 UTC, merged