added support for QueryStringQuery in rollups
opensearch-project/index-management pull request #616
Opened 2022-11-23 00:22 UTC by petardz

Signed-off-by: Petar Dzepina <petar.dzepina@vroom.com>

*Issue #, if available:*

*Description of changes:*

*CheckList:*
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/index-management/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-11-23 02:04 UTC, deshsidd commented
FYI @nknize @rishabhmaurya @sbcd90

2022-12-08 14:36 UTC, deshsidd commented on src/main/kotlin/org/opensearch/indexmanagement/rollup/interceptor/RollupInterceptor.kt
> +                        RollupFieldMapping(RollupFieldMapping.Companion.FieldType.DIMENSION, it.toString(), Dimension.Type.TERMS.type)
Why are we hardcoding this to DIMENSION and Type to TERMS?

2022-12-08 14:41 UTC, deshsidd commented on src/main/kotlin/org/opensearch/indexmanagement/rollup/util/QueryShardContextFactory.kt
> +    fun createShardContext(indexName: String?): QueryShardContext {
@nknize Are we initializing all these attributes correctly?

2022-12-20 02:33 UTC, sbcd90 requested changes

2022-12-20 02:33 UTC, sbcd90 commented on src/main/kotlin/org/opensearch/indexmanagement/rollup/util/QueryShardContextFactory.kt
> +        )
can we split `MapperService` creation part in a separate method? 
can we rename this factory object to something more meaningful or add some javadoc that this only creates a `dummy QueryShardContext` & it is only used to `retrieve field names from query string queries`.

2022-12-20 02:33 UTC, sbcd90 commented on src/main/kotlin/org/opensearch/indexmanagement/rollup/util/RollupUtils.kt
> +        }
i think we also need to implement `getRegexpQuery` https://github.com/opensearch-project/OpenSearch/blob/306b199b5e85124b953c080fe474e3c34ad0f5bc/server/src/main/java/org/opensearch/index/search/QueryStringQueryParser.java#L752

2022-12-20 02:33 UTC, sbcd90 commented on src/test/kotlin/org/opensearch/indexmanagement/rollup/interceptor/RollupInterceptorIT.kt
> +                        "query": "RatecodeID:>=1 AND RatecodeID:<=10"
can we have test cases for all types of query string query possible? there are only 6 types as per the code below.

```
override fun getFuzzyQuery(field: String?, termStr: String?, minSimilarity: Float): Query? {
            return super.getFuzzyQuery(fieldRewriteFn(field), termStr, minSimilarity)
        }
        override fun getPrefixQuery(field: String?, termStr: String?): Query {
            return super.getPrefixQuery(fieldRewriteFn(field), termStr)
        }
        override fun getFieldQuery(field: String?, queryText: String?, quoted: Boolean): Query {
            return super.getFieldQuery(fieldRewriteFn(field), queryText, quoted)
        }
        override fun getWildcardQuery(field: String?, termStr: String?): Query {
            return super.getWildcardQuery(fieldRewriteFn(field), termStr)
        }
        override fun getFieldQuery(field: String?, queryText: String?, slop: Int): Query {
            return super.getFieldQuery(fieldRewriteFn(field), queryText, slop)
   }
        override fun getRangeQuery(field: String?, part1: String?, part2: String?, startInclusive: Boolean, endInclusive: Boolean): Query {
            return super.getRangeQuery(fieldRewriteFn(field), part1, part2, startInclusive, endInclusive)
        }
```

2022-12-20 02:33 UTC, sbcd90 commented on src/main/kotlin/org/opensearch/indexmanagement/rollup/util/QueryShardContextFactory.kt
> +    }
also i see we're creating objects of `MapperService` & `QueryShardContext` everytime. is it required?
i do see the

```
object QueryShardContextFactory
```
though.

2023-01-03 20:11 UTC, petardz commented on src/test/kotlin/org/opensearch/indexmanagement/rollup/interceptor/RollupInterceptorIT.kt
> +                        "query": "RatecodeID:>=1 AND RatecodeID:<=10"
done!

2023-01-03 20:30 UTC, petardz commented on src/main/kotlin/org/opensearch/indexmanagement/rollup/util/RollupUtils.kt
> +        }
done!

2023-01-06 16:24 UTC, praveensameneni commented
Reference: https://github.com/opensearch-project/index-management/issues/320

2023-01-08 02:40 UTC, rishabhmaurya commented on src/main/kotlin/org/opensearch/indexmanagement/rollup/query/QueryStringQueryUtil.kt
> +object QueryStringQueryUtil {
There is some repetitive code logic present here which is similar to what we have in `QueryStringQueryBuilder` and `QueryParserHelper`. Ultimately, we want to avoid such duplication of logic to avoid maintenance overhead and variances. I don't have a clean solution to address it, but let's open an issue to discuss and avoid it wherever possible.

2023-01-08 02:40 UTC, rishabhmaurya commented on src/test/kotlin/org/opensearch/indexmanagement/rollup/interceptor/RollupInterceptorIT.kt
> +
This is great! thanks for adding extensive set of tests.

2023-01-09 11:45 UTC, petardz commented on src/main/kotlin/org/opensearch/indexmanagement/rollup/util/QueryShardContextFactory.kt
> +            indexSettings = Settings.EMPTY
added throwing exception here since we shouldn't ever get into situation where IndexMetadata is null here

2023-01-09 11:46 UTC, petardz commented on src/main/kotlin/org/opensearch/indexmanagement/rollup/query/QueryStringQueryUtil.kt
> +object QueryStringQueryUtil {
Sure. We're thinking about removing rewriting rollup terms so that might simplify this code a lot. (we might need MapperService only here)

2023-01-09 11:48 UTC, petardz commented on src/main/kotlin/org/opensearch/indexmanagement/rollup/util/QueryShardContextFactory.kt
> +    }
Hmm we could cache it and then just update mappings every time. We would have to compute mappings difference every time tho.

2023-01-09 11:51 UTC, petardz commented on src/main/kotlin/org/opensearch/indexmanagement/rollup/util/QueryShardContextFactory.kt
> +        )
added javadocs

2023-01-09 18:06 UTC, rishabhmaurya approved these changes

2023-01-09 21:21 UTC, deshsidd commented on src/main/kotlin/org/opensearch/indexmanagement/rollup/util/QueryShardContextFactory.kt
> +    }
@sbcd90 , please provide any concerns you have. If not we will close the thread. Thanks

2023-01-09 23:39 UTC, deshsidd approved these changes

2023-01-10 01:33 UTC, sbcd90 approved these changes

2023-01-10 01:34 UTC, merged