Shrink fix
opensearch-project/index-management pull request #718
Opened 2023-03-24 00:43 UTC by Angie-Zhang

*Issue #, if available:*

*Description of changes:*

*CheckList:*
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/index-management/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-04-05 17:34 UTC, Angie-Zhang commented on src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/shrink/AttemptMoveShardsStep.kt
> +        // Get original index settings; revert them back after shrink completed
write block changed to true. Revert it back to original value.

2023-04-05 21:02 UTC, Angie-Zhang commented on src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/action/ShrinkAction.kt
> +        const val LOCK_RESOURCE_TYPE = ".opendistro-ism-config-shrink"
ISM sends "job_index_name" and  "job_id" during acquiring node lock. Job scheduler merges these two to generate "_id". ISM deletes lock by sending request with"_id". Job scheduler can't set value of this variable since it gets them from ISM. 
```
{
        "_index": ".opendistro-job-scheduler-lock",
        "_id": ".opendistro-ism-config-shrink-node_name-f893d8522b8811ef621d004315f57672",
        "_score": 0.6486954,
        "_source": {
          "job_index_name": ".opendistro-ism-config",
          "job_id": "shrink-node_name-f893d8522b8811ef621d004315f57672",
          "lock_time": 1679617460,
          "lock_duration_seconds": 10800,
          "released": false
        }
      },
```

2023-04-05 22:01 UTC, bowenlan-amzn commented
Question: this is raised against 2.x, but we would also need this on main branch, right?

2023-04-05 22:13 UTC, bowenlan-amzn requested changes

2023-04-05 22:13 UTC, bowenlan-amzn commented on src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/shrink/AttemptMoveShardsStep.kt
> +            val remainingDsikSpace = getNodeFreeDiskSpaceAfterShrink(node, indexSizeInBytes, stepContext.clusterService.clusterSettings)
typo: remainingDiskSpace

2023-04-05 22:13 UTC, bowenlan-amzn commented on src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/shrink/AttemptMoveShardsStep.kt
> +    ): List<String>? {
Why resolve directly?

2023-04-05 22:13 UTC, bowenlan-amzn commented on src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/action/ShrinkAction.kt
> +        const val LOCK_RESOURCE_TYPE = ".opendistro-ism-config-shrink"
Job scheduler uses this to generate the id: https://github.com/opensearch-project/job-scheduler/blob/main/spi/src/main/java/org/opensearch/jobscheduler/spi/LockModel.java#L125-L127

To be more robust, let's use this also to generate the lock id we are going to delete

`LOCK_RESOURCE_TYPE` is used in getShrinkLockID when acquire lock, you cannot just change this

2023-04-05 22:14 UTC, Angie-Zhang commented on src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/shrink/AttemptMoveShardsStep.kt
> +    ): List<String>? {
removed.

2023-04-05 22:15 UTC, Angie-Zhang commented on src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/action/ShrinkAction.kt
> +        const val LOCK_RESOURCE_TYPE = ".opendistro-ism-config-shrink"
Please check latest codes. This is outdated.

2023-04-05 22:21 UTC, bowenlan-amzn commented on src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/util/StepUtils.kt
> +    return "$INDEX_MANAGEMENT_INDEX-$LOCK_SOURCE_JOB_ID-$nodeName"
Reuse the method from LockModel https://github.com/opensearch-project/job-scheduler/blob/main/spi/src/main/java/org/opensearch/jobscheduler/spi/LockModel.java#L125-L127

`return LockModel.generateLockId(INDEX_MANAGEMENT_INDEX, getShrinkJobID(nodeName))`

2023-04-05 22:38 UTC, Angie-Zhang commented on src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/shrink/AttemptMoveShardsStep.kt
> +            val remainingDsikSpace = getNodeFreeDiskSpaceAfterShrink(node, indexSizeInBytes, stepContext.clusterService.clusterSettings)
Fixed

2023-04-05 22:39 UTC, Angie-Zhang commented on src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/util/StepUtils.kt
> +    return "$INDEX_MANAGEMENT_INDEX-$LOCK_SOURCE_JOB_ID-$nodeName"
Updated

2023-04-05 22:40 UTC, Angie-Zhang commented
> Question: this is raised against 2.x, but we would also need this on main branch, right?

Added backport to main label

2023-04-07 00:29 UTC, lezzago reviewed
Please add a github issue for ITs around the shrink action fixes if they wont be a part of this PR.

2023-04-07 00:29 UTC, lezzago commented on src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/shrink/AttemptMoveShardsStep.kt
> +        }
Lets create a github issue for that then to ensure its tracked.

2023-04-07 00:29 UTC, lezzago commented on src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/shrink/AttemptMoveShardsStep.kt
> +            stepStatus = StepStatus.CONDITION_NOT_MET
Will this step get retried automatically or will the user have to retry this manually after seeing this message?

2023-04-07 00:29 UTC, lezzago commented on src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/shrink/AttemptMoveShardsStep.kt
> +        if (suitableNodes.isNotEmpty()) {
This if statement is not needed since if it is empty, the for loop wont run.

2023-04-07 01:09 UTC, Angie-Zhang commented on src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/shrink/AttemptMoveShardsStep.kt
> +            stepStatus = StepStatus.CONDITION_NOT_MET
ISM policy will retry this step by the retry count(3 by default) configured in policy.

2023-04-07 01:13 UTC, Angie-Zhang commented on src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/shrink/AttemptMoveShardsStep.kt
> +        if (suitableNodes.isNotEmpty()) {
removed

2023-04-07 01:23 UTC, Angie-Zhang commented
> Please add a github issue for ITs around the shrink action fixes if they wont be a part of this PR.

Created issue: https://github.com/opensearch-project/index-management/issues/730

2023-04-07 04:07 UTC, eirsep commented on src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/shrink/AttemptShrinkStep.kt
> +            cleanupAndFail(WRITE_BLOCK_FAILED_MESSAGE, "Failed to confirm write block for index: [$indexName] before sending shrink request.")
cane we add more details around which request or which policy failed in log message

2023-04-07 04:14 UTC, eirsep commented on src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/shrink/AttemptMoveShardsStep.kt
> +        if (targetIndexNameIsInvalid(context.clusterService, shrinkTargetIndexName)) return this
are we logging an error message that index name is invalid?

2023-04-07 04:15 UTC, eirsep commented on src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/shrink/AttemptMoveShardsStep.kt
> +        if (numOriginalShards == 1) {
add a debug log

2023-04-07 04:15 UTC, eirsep commented on src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/shrink/AttemptMoveShardsStep.kt
> +        if (numOriginalShards == numTargetShards) {
add a debug log

2023-04-07 04:18 UTC, eirsep commented on src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/shrink/AttemptMoveShardsStep.kt
> +            logger.info("No node has enough disk space for shrink action.")
can we log index, action/policy/request details also?

2023-04-07 04:21 UTC, eirsep commented on src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/util/StepUtils.kt
> +    return LockModel.generateLockId(
Might be a dumb question..
Will this be safe across versions?

2023-04-07 15:29 UTC, Angie-Zhang commented on src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/util/StepUtils.kt
> +    return LockModel.generateLockId(
No version related values are used here.

2023-04-07 15:53 UTC, Angie-Zhang commented on src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/shrink/AttemptMoveShardsStep.kt
> +        if (targetIndexNameIsInvalid(context.clusterService, shrinkTargetIndexName)) return this
This method throws InvalidIndexNameException

2023-04-07 15:58 UTC, Angie-Zhang commented on src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/shrink/AttemptMoveShardsStep.kt
> +            logger.info("No node has enough disk space for shrink action.")
Content of explain API and logs in following step reflect these.

2023-04-07 15:59 UTC, Angie-Zhang commented on src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/shrink/AttemptMoveShardsStep.kt
> +        if (numOriginalShards == 1) {
Content of explain API and logs in following step reflect these.

2023-04-07 15:59 UTC, Angie-Zhang commented on src/main/kotlin/org/opensearch/indexmanagement/indexstatemanagement/step/shrink/AttemptMoveShardsStep.kt
> +        if (numOriginalShards == numTargetShards) {
Content of explain API and logs in following step reflect these.

2023-04-07 22:35 UTC, bowenlan-amzn approved these changes
Thanks!

2023-04-10 16:22 UTC, lezzago approved these changes

2023-04-10 16:37 UTC, merged